name: Android CI

on:
  push:
    branches:
      - master
      - testing
      - develop
  pull_request:
    branches:
      - master
      - testing
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify the environment for the build'
        required: true
        default: 'testing'
        options:
          - production
          - testing
          - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set executable permissions
      run: chmod +x ./gradlew

    - name: Set up environment variables
      run: |
          echo "DOMAIN_SERVER_SUC=${{ env.DOMAIN_SERVER_SUC_TEST }}" >> $GITHUB_ENV
          echo "DOMAIN_USER=${{ env.DOMAIN_USER_TEST }}" >> $GITHUB_ENV
          echo "SERVICE_USERNAME=${{ env.SERVICE_USERNAME_TEST }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_TEST }}" >> $GITHUB_ENV
     

    - name: Debug environment variables
      run: |
        echo "Printing all environment variables..."
        printenv
    - name: List JAR files
      run: find . -name "*.jar"

    - name: Build the app
      shell: bash
      env:
        SERVICE_USERNAME: ${{ env.SERVICE_USERNAME }}
        PASSWORD: ${{ env.PASSWORD }}
        DOMAIN_SERVER_SUC: ${{ env.DOMAIN_SERVER_SUC }}
        DOMAIN_USER: ${{ env.DOMAIN_USER }}
      run: ./gradlew assembleRelease --info --stacktrace -x lint
    - name: Debug environment variables1
      run: |
        echo "Printing all environment variables..."
        printenv
    - name: Debugging information
      run: |
        echo "Classpath:"
        ./gradlew -q dependencies app:dependencies --configuration releaseRuntimeClasspath
        echo "Checking APK contents:"
        unzip -l app/build/outputs/apk/release/app-release-unsigned.apk 

    - name: List APK files
      run: ls -la app/build/outputs/apk/release/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
