name: Android CI

on:
  push:
    branches:
      - master
      - testing
      - develop
  pull_request:
    branches:
      - master
      - testing
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set executable permissions
      run: chmod +x ./gradlew

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "build-tools;30.0.3" "platforms;android-30"

    - name: Set up environment variables
      run: |
        if [[ $GITHUB_REF == refs/heads/master ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "DOMAIN_SERVER_SUC=${{ secrets.DOMAIN_SERVER_SUC_PROD }}" >> $GITHUB_ENV
          echo "DOMAIN_USER=${{ secrets.DOMAIN_USER_PROD }}" >> $GITHUB_ENV
          echo "SERVICE_USERNAME=${{ secrets.SERVICE_USERNAME_PROD }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_PROD }}" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/heads/testing ]]; then
          echo "ENVIRONMENT=testing" >> $GITHUB_ENV
          echo "DOMAIN_SERVER_SUC=${{ secrets.DOMAIN_SERVER_SUC_TEST }}" >> $GITHUB_ENV
          echo "DOMAIN_USER=${{ secrets.DOMAIN_USER_TEST }}" >> $GITHUB_ENV
          echo "SERVICE_USERNAME=${{ secrets.SERVICE_USERNAME_TEST }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_TEST }}" >> $GITHUB_ENV
        elif [[ $GITHUB_REF == refs/heads/develop ]]; then
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
          echo "DOMAIN_SERVER_SUC=${{ secrets.DOMAIN_SERVER_SUC_DESA }}" >> $GITHUB_ENV
          echo "DOMAIN_USER=${{ secrets.DOMAIN_USER_DESA }}" >> $GITHUB_ENV
          echo "SERVICE_USERNAME=${{ secrets.SERVICE_USERNAME_DESA }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD_DESA }}" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: ./gradlew clean build --refresh-dependencies

    - name: List JAR files
      run: find . -name "*.jar"

    - name: Build the app
      shell: bash
      env:
        SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        DOMAIN_SERVER_SUC: ${{ env.DOMAIN_SERVER_SUC }}
        DOMAIN_USER: ${{ env.DOMAIN_USER }}
        PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
      run: ./gradlew assembleRelease --info --stacktrace -x lint

    - name: Debugging information
      run: |
        echo "Classpath:"
        ./gradlew -q dependencies app:dependencies --configuration releaseRuntimeClasspath
        echo "Checking APK contents:"
        unzip -l app/build/outputs/apk/release/app-release-unsigned.apk 

    - name: List APK files
      run: ls -la app/build/outputs/apk/release/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
