name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set executable permissions
      run: chmod +x ./gradlew

    - name: Escape and set environment variables
      run: |
        USERNAME_ESCAPED=$(echo ${{ secrets.USERNAME_PROD }} | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
        PASSWORD_ESCAPED=$(echo ${{ secrets.PASSWORD_PROD }} | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
        echo "USERNAME_PROD=${USERNAME_ESCAPED}" >> $GITHUB_ENV
        echo "PASSWORD_PROD=${PASSWORD_ESCAPED}" >> $GITHUB_ENV

    - name: Install Android SDK Build-Tools
      run: sdkmanager "build-tools;30.0.3"

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Build the app
      shell: bash
      env:
        USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
        PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
      run: ./gradlew assembleRelease --debug --stacktrace

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
