name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set executable permissions
      run: chmod +x ./gradlew

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30"

    - name: Set up environment variables
      run: |
        echo "USERNAME_PROD=${{ secrets.USERNAME_PROD }}" >> $GITHUB_ENV
        echo "PASSWORD_PROD=${{ secrets.PASSWORD_PROD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Build the app
      shell: bash
      env:
        USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
        PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
      run: ./gradlew assembleRelease --debug --stacktrace

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
