name: Android CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
      USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
      PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Check for JAR inclusion in APK
      run: |
        echo "Classpath:"
        ./gradlew -q dependencies app:dependencies --configuration releaseRuntimeClasspath
        echo "Checking APK contents for BasicCryptoProvider:"
        if unzip -l app/build/outputs/apk/release/app-release-unsigned.apk | grep -q "BasicCryptoProvider"; then
          echo "BasicCryptoProvider is present in the APK."
        else
          echo "Error: BasicCryptoProvider is missing in the APK."
          exit 1
        fi
