name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up environment variables
      run: echo "USERNAME_PROD=${{ secrets.USERNAME_PROD }}" >> $GITHUB_ENV
      run: echo "PASSWORD_PROD=${{ secrets.PASSWORD_PROD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Build the app
      env:
        USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
        PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
      run: ./gradlew assembleRelease

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
