name: Build Android Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: '33'
        build-tools: '33.0.0'

    - name: Decode JKS file
      run: echo $JKS_BASE64 | base64 -d > TabKT.jks
      env:
        JKS_BASE64: ${{ secrets.JKS_BASE64 }}

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        JKS_BASE64: ${{ secrets.JKS_BASE64 }}
        # Puedes añadir otras variables de entorno necesarias aquí

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk
